const users = [
  {
    id: 1,
    firstName: "Juan",
    lastName: "Pérez",
    email: "juan.perez@example.com",
    age: 28,
  },
  {
    id: 2,
    firstName: "María",
    lastName: "Sánchez",
    email: "maria.sanchez@example.com",
    age: 34,
  },
  {
    id: 3,
    firstName: "Miguel",
    lastName: "García",
    email: "miguel.garcia@example.com",
    age: 45,
  },
  {
    id: 4,
    firstName: "Emilia",
    lastName: "Díaz",
    email: "emilia.diaz@example.com",
    age: 22,
  },
  {
    id: 5,
    firstName: "Roberto",
    lastName: "Moreno",
    email: "roberto.moreno@example.com",
    age: 37,
  },
  {
    id: 6,
    firstName: "Laura",
    lastName: "Ramírez",
    email: "laura.ramirez@example.com",
    age: 30,
  },
  {
    id: 7,
    firstName: "Guillermo",
    lastName: "Martínez",
    email: "guillermo.martinez@example.com",
    age: 50,
  },
  {
    id: 8,
    firstName: "Sofía",
    lastName: "González",
    email: "sofia.gonzalez@example.com",
    age: 27,
  },
  {
    id: 9,
    firstName: "Jaime",
    lastName: "López",
    email: "jaime.lopez@example.com",
    age: 42,
  },
  {
    id: 10,
    firstName: "Olivia",
    lastName: "García",
    email: "olivia.garcia@example.com",
    age: 19,
  },
  {
    id: 10,
    firstName: "Emilia",
    lastName: "Díaz",
    email: "emilia.diaz@example.com",
    age: 22,
  },
];
export default users;
